import React, { useState, useCallback, useRef } from 'react';
import {
  View, Text, TouchableOpacity, StyleSheet, ScrollView,
  ActivityIndicator, Alert, Dimensions, Modal,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect } from '@react-navigation/native';
import BarChart from '../components/BarChart';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import {
  getAttendanceByDateRange,
  getWeeklyStats,
  getTodayStats,
  type AttendanceRow,
} from '../services/DatabaseService';
import { COLORS, FONT_SIZE, FONT_WEIGHT, TRACKING, RADIUS, SPACING } from '../theme';
import Card from '../components/Card';
import Button from '../components/Button';
import SectionLabel from '../components/SectionLabel';

const { width } = Dimensions.get('window');
const SUMMARY_CARD_WIDTH = (width - SPACING.screen * 2 - SPACING.card) / 2;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function startOfDay(d: Date): Date {
  const r = new Date(d); r.setHours(0, 0, 0, 0); return r;
}
function endOfDay(d: Date): Date {
  const r = new Date(d); r.setHours(23, 59, 59, 999); return r;
}
function fmtDate(d: Date): string {
  return d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
}

function groupByDate(rows: AttendanceRow[]): { date: string; items: AttendanceRow[] }[] {
  const map: Record<string, AttendanceRow[]> = {};
  for (const r of rows) {
    if (!map[r.date]) map[r.date] = [];
    map[r.date].push(r);
  }
  return Object.entries(map).map(([date, items]) => ({ date, items }));
}

function workerTotals(rows: AttendanceRow[]): { name: string; employeeId: string; count: number }[] {
  const map: Record<string, { name: string; employeeId: string; count: number }> = {};
  for (const r of rows) {
    const key = r.employeeId || r.workerName;
    if (!map[key]) map[key] = { name: r.workerName, employeeId: r.employeeId, count: 0 };
    map[key].count++;
  }
  return Object.values(map).sort((a, b) => b.count - a.count);
}

// ─── Export builders ──────────────────────────────────────────────────────────

function buildCSV(rows: AttendanceRow[]): string {
  const header = 'Name,Employee ID,Date,Time,Day';
  const lines  = rows.map(r =>
    [`"${r.workerName}"`, `"${r.employeeId}"`, `"${r.date}"`, `"${r.time}"`, `"${r.day}"`].join(',')
  );
  return [header, ...lines].join('\n');
}

function buildPdfHtml(rows: AttendanceRow[], rangeLabel: string): string {
  const uniqueWorkers = new Set(rows.map(r => r.employeeId || r.workerName)).size;
  const dateRange     = rows.length ? `${rows[rows.length - 1].date} – ${rows[0].date}` : '—';
  const tableRows = rows.map((r, i) => `
    <tr style="background:${i % 2 === 0 ? '#f8fafc' : '#ffffff'}">
      <td>${r.workerName}</td><td>${r.employeeId || '—'}</td>
      <td>${r.date}</td><td>${r.time}</td><td>${r.day}</td>
    </tr>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:-apple-system,Helvetica,Arial,sans-serif;color:#1e293b;padding:32px}
  .header{display:flex;align-items:center;justify-content:space-between;margin-bottom:28px;border-bottom:2px solid #2563eb;padding-bottom:16px}
  .brand{font-size:26px;font-weight:800;color:#1d4ed8;letter-spacing:-0.5px}
  .brand span{color:#64748b;font-size:14px;font-weight:400;display:block;margin-top:2px}
  .stats{display:flex;gap:24px;margin-bottom:24px}
  .stat{background:#f1f5f9;border-radius:10px;padding:14px 20px;flex:1}
  .stat-n{font-size:28px;font-weight:800;color:#2563eb}
  .stat-l{font-size:12px;color:#64748b;margin-top:2px;text-transform:uppercase;letter-spacing:.5px}
  table{width:100%;border-collapse:collapse;font-size:13px}
  thead tr{background:#1d4ed8;color:#fff}
  th,td{text-align:left;padding:10px 12px;border-bottom:1px solid #e2e8f0}
  th{font-weight:700;letter-spacing:.4px}
  .footer{margin-top:24px;font-size:11px;color:#94a3b8;text-align:center}
</style></head><body>
  <div class="header">
    <div><div class="brand">NetraX <span>Attendance Report — ${rangeLabel}</span></div></div>
    <div style="font-size:12px;color:#64748b">Generated: ${new Date().toLocaleString('en-IN')}</div>
  </div>
  <div class="stats">
    <div class="stat"><div class="stat-n">${rows.length}</div><div class="stat-l">Total Records</div></div>
    <div class="stat"><div class="stat-n">${uniqueWorkers}</div><div class="stat-l">Unique Workers</div></div>
    <div class="stat" style="flex:2"><div class="stat-n" style="font-size:18px">${dateRange}</div><div class="stat-l">Date Range</div></div>
  </div>
  <table>
    <thead><tr><th>Name</th><th>Employee ID</th><th>Date</th><th>Time</th><th>Day</th></tr></thead>
    <tbody>${tableRows}</tbody>
  </table>
  <div class="footer">Generated by NetraX 2.0 · Face Recognition Attendance System</div>
</body></html>`;
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function AttendanceReportScreen() {
  const defaultTo   = endOfDay(new Date());
  const defaultFrom = startOfDay(new Date(Date.now() - 6 * 86_400_000));
  const [fromDate, setFromDate] = useState(defaultFrom);
  const [toDate,   setToDate]   = useState(defaultTo);

  const [pickerTarget, setPickerTarget] = useState<'from' | 'to' | null>(null);
  const [pickerDay,    setPickerDay]    = useState(1);
  const [pickerMonth,  setPickerMonth]  = useState(1);
  const [pickerYear,   setPickerYear]   = useState(new Date().getFullYear());

  const openPicker = (target: 'from' | 'to') => {
    const d = target === 'from' ? fromDate : toDate;
    setPickerDay(d.getDate());
    setPickerMonth(d.getMonth() + 1);
    setPickerYear(d.getFullYear());
    setPickerTarget(target);
  };

  const confirmPicker = () => {
    const daysInMonth = new Date(pickerYear, pickerMonth, 0).getDate();
    const safeDay     = Math.min(pickerDay, daysInMonth);
    const d           = new Date(pickerYear, pickerMonth - 1, safeDay);
    if (pickerTarget === 'from') setFromDate(startOfDay(d));
    else setToDate(endOfDay(d));
    setPickerTarget(null);
  };

  const stepField = (field: 'day' | 'month' | 'year', delta: number) => {
    if (field === 'day') {
      const daysInMonth = new Date(pickerYear, pickerMonth, 0).getDate();
      setPickerDay(d => Math.max(1, Math.min(daysInMonth, d + delta)));
    } else if (field === 'month') {
      setPickerMonth(m => m + delta < 1 ? 12 : m + delta > 12 ? 1 : m + delta);
    } else {
      const now = new Date().getFullYear();
      setPickerYear(y => Math.max(now - 5, Math.min(now, y + delta)));
    }
  };

  const MONTH_NAMES = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

  const [rows,    setRows]    = useState<AttendanceRow[]>([]);
  const [weekly,  setWeekly]  = useState<{ day: string; count: number }[]>([]);
  const [todaySt, setTodaySt] = useState({ total: 0, present: 0, absent: 0 });
  const [loading, setLoading] = useState(true);
  const [busy,    setBusy]    = useState<'csv' | 'pdf' | 'xls' | null>(null);

  const loadAll = useCallback(async (from: Date, to: Date) => {
    setLoading(true);
    try {
      const [r, w, t] = await Promise.all([
        getAttendanceByDateRange(startOfDay(from).getTime(), endOfDay(to).getTime()),
        getWeeklyStats(),
        getTodayStats(),
      ]);
      setRows(r);
      setWeekly(w);
      setTodaySt(t);
    } catch (e: any) {
      Alert.alert('Error', e.message);
    } finally {
      setLoading(false);
    }
  }, []);

  const fromDateRef = useRef(fromDate);
  const toDateRef   = useRef(toDate);
  fromDateRef.current = fromDate;
  toDateRef.current   = toDate;

  useFocusEffect(useCallback(() => { loadAll(fromDateRef.current, toDateRef.current); }, []));

  const applyRange = () => loadAll(fromDate, toDate);

  const rangeLabel = `${fmtDate(fromDate)} – ${fmtDate(toDate)}`;
  const slug       = `${fromDate.toISOString().slice(0, 10)}_${toDate.toISOString().slice(0, 10)}`;

  const share = async (uri: string, mime: string, title: string) => {
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri, { mimeType: mime, dialogTitle: title });
    } else {
      Alert.alert('Saved', 'File saved to documents.');
    }
  };

  const handleCSV = async () => {
    if (!rows.length) { Alert.alert('No Data', 'No records in selected range.'); return; }
    setBusy('csv');
    try {
      const uri = (FileSystem.documentDirectory ?? '') + `netrax_${slug}.csv`;
      await FileSystem.writeAsStringAsync(uri, buildCSV(rows), { encoding: FileSystem.EncodingType.UTF8 });
      await share(uri, 'text/csv', 'Export CSV');
    } catch (e: any) { Alert.alert('Export Failed', e.message); }
    finally { setBusy(null); }
  };

  const handlePDF = async () => {
    if (!rows.length) { Alert.alert('No Data', 'No records in selected range.'); return; }
    setBusy('pdf');
    try {
      const { uri: tmp } = await Print.printToFileAsync({ html: buildPdfHtml(rows, rangeLabel) });
      const dest = (FileSystem.documentDirectory ?? '') + `netrax_${slug}.pdf`;
      await FileSystem.moveAsync({ from: tmp, to: dest });
      await share(dest, 'application/pdf', 'Export PDF');
    } catch (e: any) { Alert.alert('Export Failed', e.message); }
    finally { setBusy(null); }
  };

  const handleXLS = async () => {
    if (!rows.length) { Alert.alert('No Data', 'No records in selected range.'); return; }
    setBusy('xls');
    try {
      const uri = (FileSystem.documentDirectory ?? '') + `netrax_${slug}.xls`;
      await FileSystem.writeAsStringAsync(uri, buildCSV(rows), { encoding: FileSystem.EncodingType.UTF8 });
      await share(uri, 'application/vnd.ms-excel', 'Export Excel');
    } catch (e: any) { Alert.alert('Export Failed', e.message); }
    finally { setBusy(null); }
  };

  const rate    = todaySt.total > 0 ? Math.round((todaySt.present / todaySt.total) * 100) : 0;
  const groups  = groupByDate(rows);
  const totals  = workerTotals(rows);
  const barData = weekly.map(d => ({ x: d.day, y: Math.max(d.count, 0) }));

  const summaryCards = [
    { label: 'Enrolled', value: todaySt.total,   color: COLORS.primary },
    { label: 'Present',  value: todaySt.present, color: COLORS.success },
    { label: 'Absent',   value: todaySt.absent,  color: COLORS.error   },
    { label: 'Rate',     value: `${rate}%`,      color: COLORS.warning },
  ];

  return (
    <SafeAreaView style={styles.root} edges={['left', 'right']}>
      <ScrollView
        style={styles.container}
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        {/* Analytics dashboard */}
        <SectionLabel title="TODAY'S OVERVIEW" />
        <View style={styles.summaryGrid}>
          {summaryCards.map(card => (
            <Card key={card.label} accentColor={card.color} style={styles.summaryCard}>
              <Text style={[styles.summaryValue, { color: card.color }]}>{card.value}</Text>
              <Text style={styles.summaryLabel}>{card.label}</Text>
            </Card>
          ))}
        </View>

        <SectionLabel title="7-DAY ATTENDANCE" />
        <Card noPadding style={styles.chartCard}>
          <BarChart data={barData} />
        </Card>

        {/* Date range picker */}
        <SectionLabel title="DATE RANGE" />
        <Card style={styles.dateRangeCard}>
          <View style={styles.dateRow}>
            <View style={styles.datePicker}>
              <Text style={styles.datePickerLabel}>FROM</Text>
              <TouchableOpacity style={styles.dateBtn} onPress={() => openPicker('from')} activeOpacity={0.75}>
                <Text style={styles.dateBtnText}>{fmtDate(fromDate)}</Text>
              </TouchableOpacity>
            </View>

            <View style={styles.dateArrow}>
              <Text style={styles.dateArrowText}>→</Text>
            </View>

            <View style={styles.datePicker}>
              <Text style={styles.datePickerLabel}>TO</Text>
              <TouchableOpacity style={styles.dateBtn} onPress={() => openPicker('to')} activeOpacity={0.75}>
                <Text style={styles.dateBtnText}>{fmtDate(toDate)}</Text>
              </TouchableOpacity>
            </View>
          </View>

          <Button label="Apply Range" onPress={applyRange} variant="secondary" style={styles.applyBtn} />
        </Card>

        {/* Custom date picker modal */}
        <Modal visible={pickerTarget !== null} transparent animationType="fade" onRequestClose={() => setPickerTarget(null)}>
          <View style={styles.modalOverlay}>
            <Card style={styles.modalCard}>
              <View style={styles.modalHeader}>
                <Text style={styles.modalTitle}>Select {pickerTarget === 'from' ? 'From' : 'To'} Date</Text>
                <TouchableOpacity onPress={() => setPickerTarget(null)} hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}>
                  <Text style={styles.modalClose}>✕</Text>
                </TouchableOpacity>
              </View>

              {(['year', 'month', 'day'] as const).map(field => (
                <View key={field} style={styles.stepRow}>
                  <Text style={styles.stepLabel}>{field.toUpperCase()}</Text>
                  <View style={styles.stepControls}>
                    <TouchableOpacity style={styles.stepBtn} onPress={() => stepField(field, -1)} activeOpacity={0.75}>
                      <Text style={styles.stepBtnText}>‹</Text>
                    </TouchableOpacity>
                    <Text style={styles.stepValue}>
                      {field === 'month' ? MONTH_NAMES[pickerMonth - 1] : field === 'day' ? String(pickerDay).padStart(2, '0') : pickerYear}
                    </Text>
                    <TouchableOpacity style={styles.stepBtn} onPress={() => stepField(field, 1)} activeOpacity={0.75}>
                      <Text style={styles.stepBtnText}>›</Text>
                    </TouchableOpacity>
                  </View>
                </View>
              ))}

              <Button label="Confirm" onPress={confirmPicker} style={styles.modalConfirm} />
            </Card>
          </View>
        </Modal>

        {/* Records section */}
        <SectionLabel title={`RECORDS · ${rangeLabel}`} />

        {loading ? (
          <ActivityIndicator size="large" color={COLORS.primary} style={styles.loadingSpinner} />
        ) : rows.length === 0 ? (
          <View style={styles.empty}>
            <Text style={styles.emptyIcon}>📋</Text>
            <Text style={styles.emptyText}>No records in range</Text>
            <Text style={styles.emptySubText}>Try a wider date range or mark attendance first</Text>
          </View>
        ) : (
          <>
            <Card style={styles.summaryBar}>
              <View style={styles.summaryBarItem}>
                <Text style={styles.summaryBarNum}>{rows.length}</Text>
                <Text style={styles.summaryBarLbl}>Records</Text>
              </View>
              <View style={styles.summaryBarDivider} />
              <View style={styles.summaryBarItem}>
                <Text style={styles.summaryBarNum}>{totals.length}</Text>
                <Text style={styles.summaryBarLbl}>Workers</Text>
              </View>
              <View style={styles.summaryBarDivider} />
              <View style={styles.summaryBarItem}>
                <Text style={styles.summaryBarNum}>{groups.length}</Text>
                <Text style={styles.summaryBarLbl}>Days</Text>
              </View>
            </Card>

            <SectionLabel title="BY WORKER" />
            <Card noPadding style={styles.totalsCard}>
              {totals.map((t, i) => (
                <View key={t.employeeId + i} style={[styles.totalRow, i < totals.length - 1 && styles.totalRowBorder]}>
                  <View style={styles.totalLeft}>
                    <Text style={styles.totalName}>{t.name}</Text>
                    <Text style={styles.totalEmpId}>{t.employeeId || '—'}</Text>
                  </View>
                  <View style={styles.totalBadge}>
                    <Text style={styles.totalBadgeText}>{t.count}</Text>
                  </View>
                </View>
              ))}
            </Card>

            <SectionLabel title="ATTENDANCE LOG" />
            {groups.map(group => (
              <View key={group.date} style={styles.dateGroup}>
                <View style={styles.dateHeader}>
                  <Text style={styles.dateHeaderText}>{group.date}</Text>
                  <Text style={styles.dateHeaderCount}>{group.items.length} scans</Text>
                </View>
                <Card noPadding style={styles.dateCard}>
                  {group.items.map((r, i) => (
                    <View key={r.timestamp + i} style={[styles.recordRow, i < group.items.length - 1 && styles.recordRowBorder]}>
                      <View style={styles.recordLeft}>
                        <Text style={styles.recordName}>{r.workerName}</Text>
                        <Text style={styles.recordEmpId}>{r.employeeId || '—'}</Text>
                      </View>
                      <View style={styles.recordRight}>
                        <Text style={styles.recordTime}>{r.time}</Text>
                        <Text style={styles.recordDay}>{r.day.slice(0, 3)}</Text>
                      </View>
                    </View>
                  ))}
                </Card>
              </View>
            ))}
          </>
        )}
        <View style={styles.scrollEnd} />
      </ScrollView>

      {/* Fixed export bar */}
      <View style={styles.actionBar}>
        <ExportBtn label="CSV"   color={COLORS.success} busy={busy === 'csv'} onPress={handleCSV} anyBusy={!!busy} />
        <ExportBtn label="PDF"   color={COLORS.error}   busy={busy === 'pdf'} onPress={handlePDF} anyBusy={!!busy} />
        <ExportBtn label="Excel" color={COLORS.warning} busy={busy === 'xls'} onPress={handleXLS} anyBusy={!!busy} />
      </View>
    </SafeAreaView>
  );
}

// ─── Sub-components ───────────────────────────────────────────────────────────

function ExportBtn({
  label, color, busy, anyBusy, onPress,
}: {
  label: string; color: string; busy: boolean; anyBusy: boolean; onPress: () => void;
}) {
  return (
    <TouchableOpacity
      style={[styles.actionBtn, { backgroundColor: color }, (busy || anyBusy) && styles.actionBtnBusy]}
      onPress={onPress}
      disabled={anyBusy}
      activeOpacity={0.8}
    >
      {busy
        ? <ActivityIndicator size="small" color={COLORS.white} />
        : <Text style={styles.actionBtnText}>{label}</Text>
      }
    </TouchableOpacity>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  root      : { flex: 1, backgroundColor: COLORS.background },
  container : { flex: 1 },
  content   : { padding: SPACING.screen },

  // Summary cards (2×2)
  summaryGrid  : { flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.card, marginBottom: SPACING.card },
  summaryCard  : { width: SUMMARY_CARD_WIDTH },
  summaryValue : { fontSize: FONT_SIZE.xxl, fontWeight: FONT_WEIGHT.bold },
  summaryLabel : { fontSize: FONT_SIZE.xs, color: COLORS.textSecondary, fontWeight: FONT_WEIGHT.bold, textTransform: 'uppercase', letterSpacing: TRACKING.label, marginTop: 4 },

  chartCard : { paddingVertical: 8, marginBottom: SPACING.card },

  // Date range picker
  dateRangeCard   : { gap: 14, marginBottom: SPACING.card },
  dateRow         : { flexDirection: 'row', alignItems: 'center', gap: 8 },
  datePicker      : { flex: 1, gap: 6 },
  datePickerLabel : { fontSize: FONT_SIZE.xs - 1, color: COLORS.textSecondary, fontWeight: FONT_WEIGHT.bold, letterSpacing: TRACKING.caps, textTransform: 'uppercase' },
  dateBtn         : { backgroundColor: COLORS.surfaceElevated, borderRadius: RADIUS.buttonSm, paddingHorizontal: 12, paddingVertical: 10, borderWidth: 1, borderColor: COLORS.border },
  dateBtnText     : { color: COLORS.textPrimary, fontSize: FONT_SIZE.sm, fontWeight: FONT_WEIGHT.semibold },
  dateArrow       : { paddingTop: 18 },
  dateArrowText   : { color: COLORS.textTertiary, fontSize: FONT_SIZE.lg },
  applyBtn        : {},

  // Summary bar (record count row)
  summaryBar        : { flexDirection: 'row', marginBottom: SPACING.card },
  summaryBarItem    : { flex: 1, alignItems: 'center' },
  summaryBarNum     : { fontSize: FONT_SIZE.lg, fontWeight: FONT_WEIGHT.bold, color: COLORS.primary },
  summaryBarLbl     : { fontSize: FONT_SIZE.xs, color: COLORS.textSecondary, marginTop: 2, fontWeight: FONT_WEIGHT.semibold, textTransform: 'uppercase', letterSpacing: TRACKING.label },
  summaryBarDivider : { width: 1, backgroundColor: COLORS.border, marginVertical: 4 },

  // Worker totals
  totalsCard     : { marginBottom: SPACING.card },
  totalRow       : { flexDirection: 'row', alignItems: 'center', padding: SPACING.inner, gap: 12 },
  totalRowBorder : { borderBottomWidth: 1, borderBottomColor: COLORS.border },
  totalLeft      : { flex: 1 },
  totalName      : { color: COLORS.textPrimary, fontSize: FONT_SIZE.sm, fontWeight: FONT_WEIGHT.semibold },
  totalEmpId     : { color: COLORS.textTertiary, fontSize: FONT_SIZE.xs, marginTop: 1 },
  totalBadge     : { backgroundColor: COLORS.primaryGlow, borderRadius: RADIUS.sm, paddingHorizontal: 10, paddingVertical: 4, borderWidth: 1, borderColor: COLORS.primaryBorder },
  totalBadgeText : { color: COLORS.primary, fontSize: FONT_SIZE.base, fontWeight: FONT_WEIGHT.bold },

  // Date-grouped records
  dateGroup       : { marginBottom: SPACING.card },
  dateHeader      : { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6, paddingHorizontal: 2 },
  dateHeaderText  : { color: COLORS.textSecondary, fontSize: FONT_SIZE.xs, fontWeight: FONT_WEIGHT.bold, letterSpacing: TRACKING.label },
  dateHeaderCount : { color: COLORS.textTertiary, fontSize: FONT_SIZE.xs - 1 },
  dateCard        : {},
  recordRow       : { flexDirection: 'row', alignItems: 'center', padding: 12, gap: 12 },
  recordRowBorder : { borderBottomWidth: 1, borderBottomColor: COLORS.border },
  recordLeft      : { flex: 1 },
  recordName      : { color: COLORS.textPrimary, fontSize: FONT_SIZE.sm, fontWeight: FONT_WEIGHT.semibold },
  recordEmpId     : { color: COLORS.textTertiary, fontSize: FONT_SIZE.xs, marginTop: 1 },
  recordRight     : { alignItems: 'flex-end', gap: 2 },
  recordTime      : { color: COLORS.textSecondary, fontSize: FONT_SIZE.sm, fontWeight: FONT_WEIGHT.semibold },
  recordDay       : { color: COLORS.textTertiary, fontSize: FONT_SIZE.xs - 1 },

  // Empty
  loadingSpinner : { marginTop: 40, marginBottom: 40 },
  empty          : { alignItems: 'center', marginTop: 60, marginBottom: 40, gap: 10 },
  emptyIcon      : { fontSize: 44 },
  emptyText      : { color: COLORS.textPrimary, fontSize: FONT_SIZE.md, fontWeight: FONT_WEIGHT.bold },
  emptySubText   : { color: COLORS.textSecondary, fontSize: FONT_SIZE.sm, textAlign: 'center' },
  scrollEnd      : { height: 100 },

  // Modal date picker
  modalOverlay     : { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', alignItems: 'center', justifyContent: 'center', padding: SPACING.screen },
  modalCard        : { width: '100%', gap: 16 },
  modalHeader      : { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  modalTitle       : { color: COLORS.textPrimary, fontSize: FONT_SIZE.base, fontWeight: FONT_WEIGHT.bold },
  modalClose       : { color: COLORS.textSecondary, fontSize: FONT_SIZE.lg, fontWeight: FONT_WEIGHT.semibold },
  stepRow          : { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: COLORS.surfaceElevated, borderRadius: RADIUS.buttonSm, paddingHorizontal: 16, paddingVertical: 12 },
  stepLabel        : { color: COLORS.textSecondary, fontSize: FONT_SIZE.xs, fontWeight: FONT_WEIGHT.bold, letterSpacing: TRACKING.caps, width: 48 },
  stepControls     : { flexDirection: 'row', alignItems: 'center', gap: 20 },
  stepBtn          : { width: 36, height: 36, backgroundColor: COLORS.surface, borderRadius: RADIUS.sm, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: COLORS.border },
  stepBtnText      : { color: COLORS.primary, fontSize: 22, fontWeight: FONT_WEIGHT.light, lineHeight: 28 },
  stepValue        : { color: COLORS.textPrimary, fontSize: FONT_SIZE.md, fontWeight: FONT_WEIGHT.bold, minWidth: 64, textAlign: 'center' },
  modalConfirm     : { marginTop: 4 },

  // Export bar
  actionBar     : { flexDirection: 'row', gap: SPACING.card, padding: 12, paddingBottom: 20, backgroundColor: COLORS.background, borderTopWidth: 1, borderTopColor: COLORS.border },
  actionBtn     : { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 14, borderRadius: RADIUS.buttonSm },
  actionBtnBusy : { opacity: 0.5 },
  actionBtnText : { color: COLORS.white, fontSize: FONT_SIZE.sm, fontWeight: FONT_WEIGHT.bold },
});
